const armorPool: Item[] = [
    // Common (1–4)
    {
        id: 1,
        name: 'Worn Leather Vest',
        description: 'Basic leather armor used by new adventurers.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'common',
        type: 'armor',
        rate: 1,
        require: 1,
    },
    {
        id: 2,
        name: 'Rusty Chainmail',
        description: 'Old and dented chainmail with missing links.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'common',
        type: 'armor',
        rate: 1,
        require: 2,
    },
    {
        id: 3,
        name: 'Cloth Tunic',
        description: 'Offers almost no protection but is easy to wear.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'common',
        type: 'armor',
        rate: 1,
        require: 1,
    },
    {
        id: 4,
        name: 'Guard’s Vest',
        description: 'Standard issue for town militia.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'common',
        type: 'armor',
        rate: 1,
        require: 3,
    },

    // Uncommon (5–8)
    {
        id: 5,
        name: 'Iron Chestplate',
        description: 'Heavy and reliable armor of forged iron.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'armor',
        rate: 2,
        require: 4,
    },
    {
        id: 6,
        name: 'Reinforced Leather Armor',
        description: 'Upgraded leather reinforced with metal plates.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'armor',
        rate: 2,
        require: 3,
    },
    {
        id: 7,
        name: 'Bronze Shell',
        description: 'Bronze-plated protection for warriors.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'armor',
        rate: 2,
        require: 5,
    },
    {
        id: 8,
        name: 'Scout’s Mail',
        description: 'Designed for mobility and light protection.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'armor',
        rate: 2,
        require: 3,
    },

    // Rare (9–12)
    {
        id: 9,
        name: 'Knight’s Plate',
        description: 'Trusted by experienced knights in battle.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'armor',
        rate: 3,
        require: 6,
    },
    {
        id: 10,
        name: 'Forest Guardian Armor',
        description: 'Lightweight yet strong, inspired by nature.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'armor',
        rate: 3,
        require: 6,
    },
    {
        id: 11,
        name: 'Fireborn Cuirass',
        description: 'Forged with fire-resistant materials.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'armor',
        rate: 3,
        require: 7,
    },
    {
        id: 12,
        name: 'Tundra Plate',
        description: 'Built for the harshest cold environments.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'armor',
        rate: 3,
        require: 6,
    },

    // Epic (13–16)
    {
        id: 13,
        name: 'Runed Battlemail',
        description: 'Glows with faint magical protection.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'armor',
        rate: 5,
        require: 10,
    },
    {
        id: 14,
        name: 'Moonfang Armor',
        description: 'Worn by the legendary Night Stalkers.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'armor',
        rate: 5,
        require: 9,
    },
    {
        id: 15,
        name: 'Thunderplate',
        description: 'Crackles with storm energy.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'armor',
        rate: 6,
        require: 11,
    },
    {
        id: 16,
        name: 'Embersteel Mail',
        description: 'Red-hot armor for seasoned fire mages.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'armor',
        rate: 6,
        require: 12,
    },

    // Legendary (17–20)
    {
        id: 17,
        name: 'Dragonbone Armor',
        description: 'Crafted from the bones of an ancient wyrm.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'armor',
        rate: 7,
        require: 13,
    },
    {
        id: 18,
        name: 'Sunfire Plate',
        description: 'Radiates warmth and light.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'armor',
        rate: 7,
        require: 14,
    },
    {
        id: 19,
        name: 'Voidwalker’s Guard',
        description: 'Protects from even the unseen.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'armor',
        rate: 8,
        require: 15,
    },
    {
        id: 20,
        name: 'Phoenix Chestplate',
        description: 'Rises from flames with the wearer.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'armor',
        rate: 8,
        require: 16,
    },

    // Mythic (21–24)
    {
        id: 21,
        name: 'Armor of Mythril Light',
        description: 'So light it feels like wearing nothing.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'armor',
        rate: 9,
        require: 17,
    },
    {
        id: 22,
        name: 'Starlight Aegis',
        description: 'Woven from threads of the cosmos.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'armor',
        rate: 10,
        require: 18,
    },
    {
        id: 23,
        name: 'Heirloom of the Giants',
        description: 'Passed down through titan bloodlines.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'armor',
        rate: 9,
        require: 17,
    },
    {
        id: 24,
        name: 'The Heartguard',
        description: 'Protects both body and soul.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'armor',
        rate: 10,
        require: 19,
    },

    // Unique (25–28)
    {
        id: 25,
        name: 'Soulbound Plate',
        description: 'Attunes to its owner’s will.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'armor',
        rate: 10,
        require: 20,
    },
    {
        id: 26,
        name: 'Echo Mantle',
        description: 'Resonates with forgotten chants.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'armor',
        rate: 11,
        require: 20,
    },
    {
        id: 27,
        name: 'Shifting Scale',
        description: 'Changes its material at will.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'armor',
        rate: 11,
        require: 21,
    },
    {
        id: 28,
        name: 'Mirror Ward',
        description: 'Reflects more than just light.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'armor',
        rate: 12,
        require: 21,
    },

    // Cosmic (29–32)
    {
        id: 29,
        name: 'Voidweave Vestment',
        description: 'Seems to shimmer through dimensions.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'armor',
        rate: 12,
        require: 22,
    },
    {
        id: 30,
        name: 'Nova Guard',
        description: 'Born from a collapsed star.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'armor',
        rate: 13,
        require: 23,
    },
    {
        id: 31,
        name: 'Celestial Alloy Mail',
        description: 'Forged with energy from constellations.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'armor',
        rate: 13,
        require: 23,
    },
    {
        id: 32,
        name: 'Nebula Shell',
        description: 'Swirls like a distant galaxy.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'armor',
        rate: 14,
        require: 24,
    },

    // Demonic (33–36)
    {
        id: 33,
        name: 'Hellcarved Armor',
        description: 'Forged in infernal fires.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'armor',
        rate: 14,
        require: 25,
    },
    {
        id: 34,
        name: 'Demonlord Plate',
        description: 'Was once worn by a demon general.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'armor',
        rate: 15,
        require: 26,
    },
    {
        id: 35,
        name: 'Infernal Husk',
        description: 'Burns to the touch, yet shields.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'armor',
        rate: 15,
        require: 27,
    },
    {
        id: 36,
        name: 'Wicked Thornmail',
        description: 'Lashes out at attackers.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'armor',
        rate: 16,
        require: 28,
    },

    // God (37–40)
    {
        id: 37,
        name: 'Titanplate',
        description: 'Built for the hands of gods.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'god',
        type: 'armor',
        rate: 17,
        require: 30,
    },
    {
        id: 38,
        name: 'Eternity Guard',
        description: 'Said to make the wearer immortal.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'god',
        type: 'armor',
        rate: 17,
        require: 31,
    },
    {
        id: 39,
        name: 'Olympian Vest',
        description: 'Worn by champions of divine arenas.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'god',
        type: 'armor',
        rate: 18,
        require: 32,
    },
    {
        id: 40,
        name: 'Godborn Aegis',
        description: 'Mortal hands should never wield it.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'god',
        type: 'armor',
        rate: 18,
        require: 33,
    },

    // Celestial (41–44)
    {
        id: 41,
        name: 'Radiant Shell',
        description: 'Blinds enemies with divine brilliance.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'armor',
        rate: 19,
        require: 34,
    },
    {
        id: 42,
        name: 'Harmony Robes',
        description: 'Sings with the voice of the stars.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'armor',
        rate: 19,
        require: 35,
    },
    {
        id: 43,
        name: 'Celestial Bulwark',
        description: 'Embodies order and balance.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'armor',
        rate: 20,
        require: 36,
    },
    {
        id: 44,
        name: 'Crownplate of the Heavens',
        description: 'Armor of the cosmic throne.',
        image: require('@/assets/images/armor.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'armor',
        rate: 20,
        require: 37,
    }
];
