const backPool: Item[] = [
    // COMMON
    {
      id: 67,
      name: "Traveler's Cloak",
      description: "A simple, rugged cloak worn by wanderers.",
      image: "travelers_cloak.png",
      quantity: 1,
      rarity: "common",
      type: "back",
      rate: 10,
      require: 1,
    },
    {
      id: 68,
      name: "Tattered Scarf",
      description: "A worn scarf, once colorful, now faded.",
      image: "tattered_scarf.png",
      quantity: 1,
      rarity: "common",
      type: "back",
      rate: 10,
      require: 1,
    },
    {
      id: 69,
      name: "Nomad's Shroud",
      description: "A lightweight shroud for long journeys.",
      image: "nomads_shroud.png",
      quantity: 1,
      rarity: "common",
      type: "back",
      rate: 10,
      require: 1,
    },
  
    // UNCOMMON
    {
      id: 70,
      name: "Embroidered Shawl",
      description: "Delicate threads woven with protective spells.",
      image: "embroidered_shawl.png",
      quantity: 1,
      rarity: "uncommon",
      type: "back",
      rate: 8,
      require: 5,
    },
    {
      id: 71,
      name: "Feathered Mantle",
      description: "Mantle adorned with the feathers of mystic birds.",
      image: "feathered_mantle.png",
      quantity: 1,
      rarity: "uncommon",
      type: "back",
      rate: 8,
      require: 5,
    },
    {
      id: 72,
      name: "Cowl of Quiet Winds",
      description: "A cowl that muffles footsteps and whispers.",
      image: "cowl_quiet_winds.png",
      quantity: 1,
      rarity: "uncommon",
      type: "back",
      rate: 8,
      require: 5,
    },
  
    // RARE
    {
      id: 73,
      name: "Sunwoven Cape",
      description: "A radiant cape that shimmers under sunlight.",
      image: "sunwoven_cape.png",
      quantity: 1,
      rarity: "rare",
      type: "back",
      rate: 5,
      require: 10,
      buff: [{ type: "Bonus EXP", value: 3 }],
    },
    {
      id: 74,
      name: "Duskwalker Veil",
      description: "Veil worn by those who stride unseen at dusk.",
      image: "duskwalker_veil.png",
      quantity: 1,
      rarity: "rare",
      type: "back",
      rate: 5,
      require: 10,
      buff: [{ type: "Luck", value: 4 }],
    },
    {
      id: 75,
      name: "Gladiator's Banner",
      description: "Carries the spirit of countless victories.",
      image: "gladiators_banner.png",
      quantity: 1,
      rarity: "rare",
      type: "back",
      rate: 5,
      require: 10,
      buff: [{ type: "Raid Cooldown", value: 3 }],
    },
  
    // EPIC
    {
      id: 76,
      name: "Cape of Crimson Tides",
      description: "Billows as if soaked in an endless ocean.",
      image: "cape_crimson_tides.png",
      quantity: 1,
      rarity: "epic",
      type: "back",
      rate: 3,
      require: 20,
      buff: [{ type: "RNG Cooldown", value: 5 }],
    },
    {
      id: 77,
      name: "Frostveil Shroud",
      description: "Ices over the air around its wearer.",
      image: "frostveil_shroud.png",
      quantity: 1,
      rarity: "epic",
      type: "back",
      rate: 3,
      require: 20,
      buff: [{ type: "Math Cooldown", value: 5 }],
    },
    {
      id: 78,
      name: "Dawnwing Cloak",
      description: "Painted with the first light of each day.",
      image: "dawnwing_cloak.png",
      quantity: 1,
      rarity: "epic",
      type: "back",
      rate: 3,
      require: 20,
      buff: [{ type: "Bonus EXP", value: 6 }],
    },
  
    // LEGENDARY
    {
      id: 79,
      name: "Wings of the Fallen",
      description: "Made from the plumes of ancient celestial beings.",
      image: "wings_fallen.png",
      quantity: 1,
      rarity: "legendary",
      type: "back",
      rate: 2,
      require: 35,
      buff: [{ type: "Luck", value: 7 }],
    },
    {
      id: 80,
      name: "Stormcatcher's Drape",
      description: "Catches storms and weaves them into fabric.",
      image: "stormcatcher_drape.png",
      quantity: 1,
      rarity: "legendary",
      type: "back",
      rate: 2,
      require: 35,
      buff: [{ type: "Raid Cooldown", value: 6 }],
    },
    {
      id: 81,
      name: "Banner of the Last Stand",
      description: "Flies even when hope has withered.",
      image: "banner_last_stand.png",
      quantity: 1,
      rarity: "legendary",
      type: "back",
      rate: 2,
      require: 35,
      buff: [{ type: "Bonus EXP", value: 7 }],
    },
  
    // MYTHIC
    {
      id: 82,
      name: "Veil of Starfall",
      description: "Sparkles like a meteor shower in motion.",
      image: "veil_starfall.png",
      quantity: 1,
      rarity: "mythic",
      type: "back",
      rate: 1,
      require: 50,
      buff: [{ type: "Luck", value: 8 }],
    },
    {
      id: 83,
      name: "Mantle of the Worldshaper",
      description: "Bears the weight of countless dreams.",
      image: "mantle_worldshaper.png",
      quantity: 1,
      rarity: "mythic",
      type: "back",
      rate: 1,
      require: 50,
      buff: [{ type: "Bonus EXP", value: 9 }],
    },
    {
      id: 84,
      name: "Scarf of Eternal Gale",
      description: "Forever fluttering in unseen winds.",
      image: "scarf_eternal_gale.png",
      quantity: 1,
      rarity: "mythic",
      type: "back",
      rate: 1,
      require: 50,
      buff: [{ type: "Raid Cooldown", value: 8 }],
    },
  
    // UNIQUE
    {
      id: 85,
      name: "Phoenixwing Drape",
      description: "Sheds burning feathers at will.",
      image: "phoenixwing_drape.png",
      quantity: 1,
      rarity: "unique",
      type: "back",
      rate: 0.8,
      require: 70,
      buff: [{ type: "Bonus EXP", value: 10 }],
    },
    {
      id: 86,
      name: "Lunar Warden's Shroud",
      description: "Blessed by the goddess of the moon.",
      image: "lunar_wardens_shroud.png",
      quantity: 1,
      rarity: "unique",
      type: "back",
      rate: 0.8,
      require: 70,
      buff: [{ type: "Math Cooldown", value: 9 }],
    },
    {
      id: 87,
      name: "Crest of the Forgotten",
      description: "Bears a sigil no one remembers.",
      image: "crest_forgotten.png",
      quantity: 1,
      rarity: "unique",
      type: "back",
      rate: 0.8,
      require: 70,
      buff: [{ type: "Luck", value: 9 }],
    },
  
    // COSMIC
    {
      id: 88,
      name: "Nebula Mantle",
      description: "Woven from gases between galaxies.",
      image: "nebula_mantle.png",
      quantity: 1,
      rarity: "cosmic",
      type: "back",
      rate: 0.5,
      require: 100,
      buff: [{ type: "Bonus EXP", value: 12 }],
    },
    {
      id: 89,
      name: "Solarwind Wings",
      description: "Ride the radiation of newborn stars.",
      image: "solarwind_wings.png",
      quantity: 1,
      rarity: "cosmic",
      type: "back",
      rate: 0.5,
      require: 100,
      buff: [{ type: "RNG Cooldown", value: 10 }],
    },
    {
      id: 90,
      name: "Aurora Shroud",
      description: "Glows with the colors of shifting skies.",
      image: "aurora_shroud.png",
      quantity: 1,
      rarity: "cosmic",
      type: "back",
      rate: 0.5,
      require: 100,
      buff: [{ type: "Luck", value: 11 }],
    },
  
    // DEMONIC
    {
      id: 91,
      name: "Fleshweaver's Cape",
      description: "Sewn from the skins of fallen enemies.",
      image: "fleshweaver_cape.png",
      quantity: 1,
      rarity: "demonic",
      type: "back",
      rate: 0.3,
      require: 120,
      buff: [{ type: "Raid Cooldown", value: 12 }],
    },
    {
      id: 92,
      name: "Screaming Banner",
      description: "Wails when battle is near.",
      image: "screaming_banner.png",
      quantity: 1,
      rarity: "demonic",
      type: "back",
      rate: 0.3,
      require: 120,
      buff: [{ type: "Bonus EXP", value: 14 }],
    },
    {
      id: 93,
      name: "Wings of the Abyss",
      description: "Spread terror with every beat.",
      image: "wings_abyss.png",
      quantity: 1,
      rarity: "demonic",
      type: "back",
      rate: 0.3,
      require: 120,
      buff: [{ type: "Luck", value: 12 }],
    },
  
    // GOD
    {
      id: 94,
      name: "Celestial Standard",
      description: "The rallying cry of heavenly hosts.",
      image: "celestial_standard.png",
      quantity: 1,
      rarity: "god",
      type: "back",
      rate: 0.1,
      require: 150,
      buff: [{ type: "Bonus EXP", value: 18 }],
    },
    {
      id: 95,
      name: "Divine Plumage",
      description: "Feathers plucked from elder gods.",
      image: "divine_plumage.png",
      quantity: 1,
      rarity: "god",
      type: "back",
      rate: 0.1,
      require: 150,
      buff: [{ type: "Raid Cooldown", value: 15 }],
    },
    {
      id: 96,
      name: "Mantle of Providence",
      description: "Blessed with unfathomable luck.",
      image: "mantle_providence.png",
      quantity: 1,
      rarity: "god",
      type: "back",
      rate: 0.1,
      require: 150,
      buff: [{ type: "Luck", value: 15 }],
    },
  
    // CELESTIAL
    {
      id: 97,
      name: "Eclipsed Wings",
      description: "Carry the power of darkness and light.",
      image: "eclipsed_wings.png",
      quantity: 1,
      rarity: "celestial",
      type: "back",
      rate: 0.05,
      require: 200,
      buff: [{ type: "Bonus EXP", value: 25 }],
    },
    {
      id: 98,
      name: "Aethercloak",
      description: "Shimmers between worlds.",
      image: "aethercloak.png",
      quantity: 1,
      rarity: "celestial",
      type: "back",
      rate: 0.05,
      require: 200,
      buff: [{ type: "Math Cooldown", value: 20 }],
    },
    {
      id: 99,
      name: "Stardust Banner",
      description: "March beneath the falling stars.",
      image: "stardust_banner.png",
      quantity: 1,
      rarity: "celestial",
      type: "back",
      rate: 0.05,
      require: 200,
      buff: [{ type: "Luck", value: 20 }],
    },
  ];
  