const helmetPool: Item[] = [
    // Common
    {
        id: 101,
        name: 'Worn Leather Cap',
        description: 'A matching headpiece for the Worn Leather Vest.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'common',
        type: 'helmet',
        rate: 1,
        require: 1,
    },
    {
        id: 102,
        name: 'Rusty Chain Hood',
        description: 'Offers minimal protection, fits the Rusty Chainmail.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'common',
        type: 'helmet',
        rate: 1,
        require: 2,
    },
    {
        id: 103,
        name: 'Cloth Headwrap',
        description: 'Basic wrap for novices wearing the Cloth Tunic.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'common',
        type: 'helmet',
        rate: 1,
        require: 1,
    },
    {
        id: 104,
        name: 'Guard’s Helm',
        description: 'Standard issue helm for local militia.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'common',
        type: 'helmet',
        rate: 1,
        require: 3,
    },

    // Uncommon
    {
        id: 105,
        name: 'Iron Helmet',
        description: 'Sturdy headgear for the Iron Chestplate.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'helmet',
        rate: 2,
        require: 4,
    },
    {
        id: 106,
        name: 'Reinforced Leather Hood',
        description: 'Protective hood reinforced with metal.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'helmet',
        rate: 2,
        require: 3,
    },
    {
        id: 107,
        name: 'Bronze Visor',
        description: 'Helm to match the Bronze Shell armor.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'helmet',
        rate: 2,
        require: 5,
    },
    {
        id: 108,
        name: 'Scout’s Hood',
        description: 'Light headwear for fast movement.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'helmet',
        rate: 2,
        require: 3,
    },

    // Rare
    {
        id: 109,
        name: 'Knight’s Helm',
        description: 'Traditional helm worn by seasoned knights.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'helmet',
        rate: 3,
        require: 6,
    },
    {
        id: 110,
        name: 'Forest Guardian Hood',
        description: 'Hood infused with forest energy.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'helmet',
        rate: 3,
        require: 6,
    },
    {
        id: 111,
        name: 'Fireborn Helm',
        description: 'Built to withstand blazing heat.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'helmet',
        rate: 3,
        require: 7,
    },
    {
        id: 112,
        name: 'Tundra Hood',
        description: 'Protects the head in icy climates.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'helmet',
        rate: 3,
        require: 6,
    },

    // Epic
    {
        id: 113,
        name: 'Runed Crown',
        description: 'Engraved with glowing protective runes.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'helmet',
        rate: 5,
        require: 10,
    },
    {
        id: 114,
        name: 'Moonfang Mask',
        description: 'Cloaks the face in shadow and moonlight.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'helmet',
        rate: 5,
        require: 9,
    },
    {
        id: 115,
        name: 'Thunderhelm',
        description: 'Buzzes softly with crackling energy.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'helmet',
        rate: 6,
        require: 11,
    },
    {
        id: 116,
        name: 'Embersteel Helm',
        description: 'Glows with internal heat like its chestpiece.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'helmet',
        rate: 6,
        require: 12,
    },

    // Legendary
    {
        id: 117,
        name: 'Dragonbone Helm',
        description: 'Matches the chestplate made from wyrm bones.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'helmet',
        rate: 7,
        require: 13,
    },
    {
        id: 118,
        name: 'Sunfire Circlet',
        description: 'Blazes like the sun upon the brow.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'helmet',
        rate: 7,
        require: 14,
    },
    {
        id: 119,
        name: 'Voidwalker Visage',
        description: 'Covers the face in void-black shadows.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'helmet',
        rate: 8,
        require: 15,
    },
    {
        id: 120,
        name: 'Phoenix Helm',
        description: 'Crowned in flame feathers.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'helmet',
        rate: 8,
        require: 16,
    },

    // Mythic
    {
        id: 121,
        name: 'Mythril Light Crown',
        description: 'Light as air, crafted for visionaries.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'helmet',
        rate: 9,
        require: 17,
    },
    {
        id: 122,
        name: 'Starlight Halo',
        description: 'Shimmers like a distant constellation.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'helmet',
        rate: 10,
        require: 18,
    },
    {
        id: 123,
        name: 'Giantblood Helm',
        description: 'Enormous helm passed down through titans.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'helmet',
        rate: 9,
        require: 17,
    },
    {
        id: 124,
        name: 'Heartward Visor',
        description: 'Protects the head and thoughts.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'helmet',
        rate: 10,
        require: 19,
    },

    // Unique
    {
        id: 125,
        name: 'Soulbound Helm',
        description: 'Adapts to its wearer like the armor does.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'helmet',
        rate: 10,
        require: 20,
    },
    {
        id: 126,
        name: 'Echo Hood',
        description: 'Carries ancient whispers.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'helmet',
        rate: 11,
        require: 20,
    },
    {
        id: 127,
        name: 'Shifting Helm',
        description: 'Changes form just like the armor.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'helmet',
        rate: 11,
        require: 21,
    },
    {
        id: 128,
        name: 'Mirror Helm',
        description: 'Reflects danger and style.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'helmet',
        rate: 12,
        require: 21,
    },

    // Cosmic
    {
        id: 129,
        name: 'Voidweave Hood',
        description: 'Warped fabric from beyond the stars.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'helmet',
        rate: 12,
        require: 22,
    },
    {
        id: 130,
        name: 'Nova Crown',
        description: 'Born from collapsing stars.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'helmet',
        rate: 13,
        require: 23,
    },
    {
        id: 131,
        name: 'Celestial Alloy Helm',
        description: 'Completes the Celestial Alloy Mail.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'helmet',
        rate: 13,
        require: 23,
    },
    {
        id: 132,
        name: 'Nebula Helm',
        description: 'Swirls like a starborn cloud.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'helmet',
        rate: 14,
        require: 24,
    },

    // Demonic
    {
        id: 133,
        name: 'Hellcarved Helm',
        description: 'Burned markings echo infernal power.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'helmet',
        rate: 14,
        require: 25,
    },
    {
        id: 134,
        name: 'Demonlord Horns',
        description: 'Dark helm that radiates dread.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'helmet',
        rate: 15,
        require: 26,
    },
    {
        id: 135,
        name: 'Infernal Crown',
        description: 'Forged in flames, fits with Infernal Husk.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'helmet',
        rate: 15,
        require: 27,
    },
    {
        id: 136,
        name: 'Thorned Visor',
        description: 'Strikes with vengeance when touched.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'helmet',
        rate: 16,
        require: 28,
    },

    // God
    {
        id: 137,
        name: 'Titan Helm',
        description: 'Massive helm of divine origin.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'god',
        type: 'helmet',
        rate: 17,
        require: 30,
    },
    {
        id: 138,
        name: 'Helm of Eternity',
        description: 'Said to grant visions of forever.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'god',
        type: 'helmet',
        rate: 17,
        require: 31,
    },
    {
        id: 139,
        name: 'Olympian Crown',
        description: 'Worn by demigods in sacred arenas.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'god',
        type: 'helmet',
        rate: 18,
        require: 32,
    },
    {
        id: 140,
        name: 'Helm of the Heavens',
        description: 'Paired with the Godborn Aegis.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'god',
        type: 'helmet',
        rate: 18,
        require: 33,
    },

    // Celestial
    {
        id: 141,
        name: 'Radiant Halo',
        description: 'Shines with divine clarity.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'helmet',
        rate: 19,
        require: 34,
    },
    {
        id: 142,
        name: 'Harmony Circlet',
        description: 'Carries the song of the cosmos.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'helmet',
        rate: 19,
        require: 35,
    },
    {
        id: 143,
        name: 'Celestial Crown',
        description: 'Fit for one who rules the skies.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'helmet',
        rate: 20,
        require: 36,
    },
    {
        id: 144,
        name: 'Crown of the Stars',
        description: 'Final piece of the celestial regalia.',
        image: require('@/assets/images/helmet.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'helmet',
        rate: 20,
        require: 37,
    }
];
