const mountPool: Item[] = [
    // COMMON
    {
      id: 200,
      name: "Rusty Donkey",
      description: "Stubborn but reliable in a pinch.",
      image: "rusty_donkey.png",
      quantity: 1,
      rarity: "common",
      type: "mount",
      rate: 10,
      require: 1,
    },
    {
      id: 201,
      name: "Plains Strider",
      description: "A swift beast of open fields.",
      image: "plains_strider.png",
      quantity: 1,
      rarity: "common",
      type: "mount",
      rate: 10,
      require: 1,
    },
    {
      id: 202,
      name: "Old Warhorse",
      description: "Still strong after many battles.",
      image: "old_warhorse.png",
      quantity: 1,
      rarity: "common",
      type: "mount",
      rate: 10,
      require: 1,
    },
  
    // UNCOMMON
    {
      id: 203,
      name: "Sand Lizard",
      description: "Scales shimmer under the sun.",
      image: "sand_lizard.png",
      quantity: 1,
      rarity: "uncommon",
      type: "mount",
      rate: 8,
      require: 5,
    },
    {
      id: 204,
      name: "Pine Elk",
      description: "Mighty horns crowned in moss.",
      image: "pine_elk.png",
      quantity: 1,
      rarity: "uncommon",
      type: "mount",
      rate: 8,
      require: 5,
    },
    {
      id: 205,
      name: "Highland Ram",
      description: "Tough enough to scale any mountain.",
      image: "highland_ram.png",
      quantity: 1,
      rarity: "uncommon",
      type: "mount",
      rate: 8,
      require: 5,
    },
  
    // RARE
    {
      id: 206,
      name: "Gale Raptor",
      description: "Swift as the northern winds.",
      image: "gale_raptor.png",
      quantity: 1,
      rarity: "rare",
      type: "mount",
      rate: 5,
      require: 10,
    },
    {
      id: 207,
      name: "Frosthoof Stag",
      description: "Breath steams even in summer.",
      image: "frosthoof_stag.png",
      quantity: 1,
      rarity: "rare",
      type: "mount",
      rate: 5,
      require: 10,
    },
    {
      id: 208,
      name: "Ashen Drake",
      description: "A young dragon born of embers.",
      image: "ashen_drake.png",
      quantity: 1,
      rarity: "rare",
      type: "mount",
      rate: 5,
      require: 10,
    },
  
    // EPIC
    {
      id: 209,
      name: "Thunderhorn",
      description: "Every stomp rumbles like thunder.",
      image: "thunderhorn.png",
      quantity: 1,
      rarity: "epic",
      type: "mount",
      rate: 3,
      require: 20,
    },
    {
      id: 210,
      name: "Verdant Wyrm",
      description: "A serpent of living vines.",
      image: "verdant_wyrm.png",
      quantity: 1,
      rarity: "epic",
      type: "mount",
      rate: 3,
      require: 20,
    },
    {
      id: 211,
      name: "Cinderbeast",
      description: "Born from volcanic fires.",
      image: "cinderbeast.png",
      quantity: 1,
      rarity: "epic",
      type: "mount",
      rate: 3,
      require: 20,
    },
  
    // LEGENDARY
    {
      id: 212,
      name: "Spectral Charger",
      description: "Glides through walls and mist.",
      image: "spectral_charger.png",
      quantity: 1,
      rarity: "legendary",
      type: "mount",
      rate: 2,
      require: 35,
    },
    {
      id: 213,
      name: "Phoenix Stallion",
      description: "Its mane burns with eternal flames.",
      image: "phoenix_stallion.png",
      quantity: 1,
      rarity: "legendary",
      type: "mount",
      rate: 2,
      require: 35,
    },
    {
      id: 214,
      name: "Moonhowler",
      description: "A wolf that rides moonbeams.",
      image: "moonhowler.png",
      quantity: 1,
      rarity: "legendary",
      type: "mount",
      rate: 2,
      require: 35,
    },
  
    // MYTHIC
    {
      id: 215,
      name: "Sky Leviathan",
      description: "A colossal beast swimming through clouds.",
      image: "sky_leviathan.png",
      quantity: 1,
      rarity: "mythic",
      type: "mount",
      rate: 1,
      require: 50,
    },
    {
      id: 216,
      name: "Starforged Gryphon",
      description: "Forged from the dust of dying stars.",
      image: "starforged_gryphon.png",
      quantity: 1,
      rarity: "mythic",
      type: "mount",
      rate: 1,
      require: 50,
    },
    {
      id: 217,
      name: "Void Elk",
      description: "Each step warps the space around it.",
      image: "void_elk.png",
      quantity: 1,
      rarity: "mythic",
      type: "mount",
      rate: 1,
      require: 50,
    },
  
    // UNIQUE
    {
      id: 218,
      name: "Dragonbone Direwolf",
      description: "Bones of the ancient wolves reforged.",
      image: "dragonbone_direwolf.png",
      quantity: 1,
      rarity: "unique",
      type: "mount",
      rate: 0.8,
      require: 70,
    },
    {
      id: 219,
      name: "Shadowed Wyvern",
      description: "Hidden in permanent twilight.",
      image: "shadowed_wyvern.png",
      quantity: 1,
      rarity: "unique",
      type: "mount",
      rate: 0.8,
      require: 70,
    },
    {
      id: 220,
      name: "Eclipse Charger",
      description: "Splits light and darkness underfoot.",
      image: "eclipse_charger.png",
      quantity: 1,
      rarity: "unique",
      type: "mount",
      rate: 0.8,
      require: 70,
    },
  
    // COSMIC
    {
      id: 221,
      name: "Nebula Serpent",
      description: "Coils among the galaxies.",
      image: "nebula_serpent.png",
      quantity: 1,
      rarity: "cosmic",
      type: "mount",
      rate: 0.5,
      require: 100,
    },
    {
      id: 222,
      name: "Astral Courser",
      description: "A steed made of stardust and dreams.",
      image: "astral_courser.png",
      quantity: 1,
      rarity: "cosmic",
      type: "mount",
      rate: 0.5,
      require: 100,
    },
    {
      id: 223,
      name: "Comet Chaser",
      description: "Races alongside shooting stars.",
      image: "comet_chaser.png",
      quantity: 1,
      rarity: "cosmic",
      type: "mount",
      rate: 0.5,
      require: 100,
    },
  
    // DEMONIC
    {
      id: 224,
      name: "Hellcharger",
      description: "Fires blaze from its nostrils.",
      image: "hellcharger.png",
      quantity: 1,
      rarity: "demonic",
      type: "mount",
      rate: 0.3,
      require: 120,
    },
    {
      id: 225,
      name: "Blightwing Manticore",
      description: "Toxic and terrifying.",
      image: "blightwing_manticore.png",
      quantity: 1,
      rarity: "demonic",
      type: "mount",
      rate: 0.3,
      require: 120,
    },
    {
      id: 226,
      name: "Infernal Basilisk",
      description: "Its gaze scorches the soul.",
      image: "infernal_basilisk.png",
      quantity: 1,
      rarity: "demonic",
      type: "mount",
      rate: 0.3,
      require: 120,
    },
  
    // GOD
    {
      id: 227,
      name: "Solar Pegasus",
      description: "Its wings blaze like the sun.",
      image: "solar_pegasus.png",
      quantity: 1,
      rarity: "god",
      type: "mount",
      rate: 0.1,
      require: 150,
    },
    {
      id: 228,
      name: "Titan's Bull",
      description: "Steps shake mountains.",
      image: "titans_bull.png",
      quantity: 1,
      rarity: "god",
      type: "mount",
      rate: 0.1,
      require: 150,
    },
    {
      id: 229,
      name: "Aurora Dragon",
      description: "Weaves aurora trails across the sky.",
      image: "aurora_dragon.png",
      quantity: 1,
      rarity: "god",
      type: "mount",
      rate: 0.1,
      require: 150,
    },
  
    // CELESTIAL
    {
      id: 230,
      name: "Seraphim Steed",
      description: "A holy beast of pure light.",
      image: "seraphim_steed.png",
      quantity: 1,
      rarity: "celestial",
      type: "mount",
      rate: 0.05,
      require: 200,
    },
    {
      id: 231,
      name: "Warden Phoenix",
      description: "Guardian of forgotten heavens.",
      image: "warden_phoenix.png",
      quantity: 1,
      rarity: "celestial",
      type: "mount",
      rate: 0.05,
      require: 200,
    },
    {
      id: 232,
      name: "Eternity Whale",
      description: "Drifts endlessly across astral oceans.",
      image: "eternity_whale.png",
      quantity: 1,
      rarity: "celestial",
      type: "mount",
      rate: 0.05,
      require: 200,
    },
  ];
  