const shoesPool: Item[] = [
    // Common
    {
        id: 201,
        name: 'Worn Leather Boots',
        description: 'Rough boots matching the Worn Leather Vest.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'common',
        type: 'shoes',
        rate: 1,
        require: 1,
    },
    {
        id: 202,
        name: 'Rusty Greaves',
        description: 'Old greaves that pair with Rusty Chainmail.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'common',
        type: 'shoes',
        rate: 1,
        require: 2,
    },
    {
        id: 203,
        name: 'Cloth Sandals',
        description: 'Light sandals worn by apprentices.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'common',
        type: 'shoes',
        rate: 1,
        require: 1,
    },
    {
        id: 204,
        name: 'Guard’s Footwear',
        description: 'Durable shoes issued to basic guards.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'common',
        type: 'shoes',
        rate: 1,
        require: 3,
    },

    // Uncommon
    {
        id: 205,
        name: 'Iron Boots',
        description: 'Solid boots to match Iron Chestplate.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'shoes',
        rate: 2,
        require: 4,
    },
    {
        id: 206,
        name: 'Reinforced Leather Boots',
        description: 'Flexible but protective footwear.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'shoes',
        rate: 2,
        require: 3,
    },
    {
        id: 207,
        name: 'Bronze Stepguards',
        description: 'Pair well with Bronze Shell armor.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'shoes',
        rate: 2,
        require: 5,
    },
    {
        id: 208,
        name: 'Scout’s Boots',
        description: 'Light boots for quick movement.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'uncommon',
        type: 'shoes',
        rate: 2,
        require: 3,
    },

    // Rare
    {
        id: 209,
        name: 'Knight’s Boots',
        description: 'Hearty boots worn by knights.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'shoes',
        rate: 3,
        require: 6,
    },
    {
        id: 210,
        name: 'Forest Guardian Boots',
        description: 'Soft soles for treading forest paths.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'shoes',
        rate: 3,
        require: 6,
    },
    {
        id: 211,
        name: 'Fireborn Boots',
        description: 'Heat-resistant soles blaze beneath.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'shoes',
        rate: 3,
        require: 7,
    },
    {
        id: 212,
        name: 'Tundra Walkers',
        description: 'Insulated shoes for icy terrain.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'rare',
        type: 'shoes',
        rate: 3,
        require: 6,
    },

    // Epic
    {
        id: 213,
        name: 'Runed Boots',
        description: 'Runes etched into the soles for speed.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'shoes',
        rate: 5,
        require: 10,
    },
    {
        id: 214,
        name: 'Moonfang Steps',
        description: 'Silent steps under moonlight.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'shoes',
        rate: 5,
        require: 9,
    },
    {
        id: 215,
        name: 'Thunderboots',
        description: 'Crackles of energy trail behind.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'shoes',
        rate: 6,
        require: 11,
    },
    {
        id: 216,
        name: 'Embersteel Boots',
        description: 'Match the heat of the Embersteel Helm.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'epic',
        type: 'shoes',
        rate: 6,
        require: 12,
    },

    // Legendary
    {
        id: 217,
        name: 'Dragonbone Boots',
        description: 'Crafted from scales of ancient wyrms.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'shoes',
        rate: 7,
        require: 13,
    },
    {
        id: 218,
        name: 'Sunfire Greaves',
        description: 'Radiate warmth and speed.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'shoes',
        rate: 7,
        require: 14,
    },
    {
        id: 219,
        name: 'Voidwalker Boots',
        description: 'Walk between realms.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'shoes',
        rate: 8,
        require: 15,
    },
    {
        id: 220,
        name: 'Phoenix Footwraps',
        description: 'Fiery feathers line the soles.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'legendary',
        type: 'shoes',
        rate: 8,
        require: 16,
    },

    // Mythic
    {
        id: 221,
        name: 'Mythril Steps',
        description: 'Lightweight but unyielding.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'shoes',
        rate: 9,
        require: 17,
    },
    {
        id: 222,
        name: 'Starlight Treads',
        description: 'They glimmer with each step.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'shoes',
        rate: 10,
        require: 18,
    },
    {
        id: 223,
        name: 'Giantblood Boots',
        description: 'Colossal shoes fit for titanic legs.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'shoes',
        rate: 9,
        require: 17,
    },
    {
        id: 224,
        name: 'Heartward Boots',
        description: 'Steady and strong footing.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'mythic',
        type: 'shoes',
        rate: 10,
        require: 19,
    },

    // Unique
    {
        id: 225,
        name: 'Soulbound Steps',
        description: 'Shoes that remember their owner.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'shoes',
        rate: 10,
        require: 20,
    },
    {
        id: 226,
        name: 'Echo Footwraps',
        description: 'Echo softly across space and time.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'shoes',
        rate: 11,
        require: 20,
    },
    {
        id: 227,
        name: 'Shifting Steps',
        description: 'Change shape with terrain.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'shoes',
        rate: 11,
        require: 21,
    },
    {
        id: 228,
        name: 'Mirror Boots',
        description: 'Reflective like polished glass.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'unique',
        type: 'shoes',
        rate: 12,
        require: 21,
    },

    // Cosmic
    {
        id: 229,
        name: 'Voidweave Sandals',
        description: 'Soft as the stars they came from.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'shoes',
        rate: 12,
        require: 22,
    },
    {
        id: 230,
        name: 'Nova Treads',
        description: 'Pulse with starlight energy.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'shoes',
        rate: 13,
        require: 23,
    },
    {
        id: 231,
        name: 'Celestial Alloy Boots',
        description: 'Light, elegant, and unbreakable.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'shoes',
        rate: 13,
        require: 23,
    },
    {
        id: 232,
        name: 'Nebula Steps',
        description: 'Swirling smoke follows your stride.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'cosmic',
        type: 'shoes',
        rate: 14,
        require: 24,
    },

    // Demonic
    {
        id: 233,
        name: 'Hellcarved Greaves',
        description: 'Searing with infernal energy.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'shoes',
        rate: 14,
        require: 25,
    },
    {
        id: 234,
        name: 'Demonlord Steps',
        description: 'Only the wicked dare wear them.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'shoes',
        rate: 15,
        require: 26,
    },
    {
        id: 235,
        name: 'Infernal Treads',
        description: 'Footprints burn into the ground.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'shoes',
        rate: 15,
        require: 27,
    },
    {
        id: 236,
        name: 'Thorned Boots',
        description: 'Inflicts pain to trespassers.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'demonic',
        type: 'shoes',
        rate: 16,
        require: 28,
    },

    // God
    {
        id: 237,
        name: 'Titan Stompers',
        description: 'For giants who stride across realms.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'god',
        type: 'shoes',
        rate: 17,
        require: 30,
    },
    {
        id: 238,
        name: 'Eternal Walkers',
        description: 'Leave no mark but last forever.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'god',
        type: 'shoes',
        rate: 17,
        require: 31,
    },
    {
        id: 239,
        name: 'Olympian Greaves',
        description: 'Worn by champions of the divine.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'god',
        type: 'shoes',
        rate: 18,
        require: 32,
    },
    {
        id: 240,
        name: 'Heavenstep Boots',
        description: 'Let you walk where gods fly.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'god',
        type: 'shoes',
        rate: 18,
        require: 33,
    },

    // Celestial
    {
        id: 241,
        name: 'Radiant Boots',
        description: 'Glow with heavenly light.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'shoes',
        rate: 19,
        require: 34,
    },
    {
        id: 242,
        name: 'Harmony Slippers',
        description: 'Even footsteps sing with grace.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'shoes',
        rate: 19,
        require: 35,
    },
    {
        id: 243,
        name: 'Celestial Striders',
        description: 'For wandering the stars.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'shoes',
        rate: 20,
        require: 36,
    },
    {
        id: 244,
        name: 'Shoes of the Stars',
        description: 'Final step in celestial journey.',
        image: require('@/assets/images/shoes.png'),
        quantity: 1,
        rarity: 'celestial',
        type: 'shoes',
        rate: 20,
        require: 37,
    }
];
